# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-09 13:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_ts',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_ts',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
